[build]
  base = "website"
  command = "npm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../{src,website}/"

# Serve JSON schema files with correct content-type
[[headers]]
  for = "/schemas/*"
  [headers.values]
    Content-Type = "application/schema+json"
    Access-Control-Allow-Origin = "*"
