blank_issues_enabled: false
contact_links:
  - name: Other questions/issues
    url: https://github.com/testOrgREGnosys/common-domain-model/discussions/new?category=q-a
    about: Please raise other questions/issues within discussions.
