name: CVE Scanning for Maven

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'pom.xml'
      - 'allow-list.xml'
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths:
      - 'pom.xml'
      - 'allow-list.xml'
      - '.github/workflows/cve-scanning.yml'

jobs:
  depcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/maven-build
      with:
        run-tests: false
    - name: CVE scanning
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      with:
        project: 'Common Domain Model'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --suppression allow-list.xml
          --failOnCVSS 7
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: CVE Scan Report
        path: ${{github.workspace}}/reports
